#Simulation options

sim.file = "Data/mountdarwin.tif" # Relative location of TIF elevation dataset

sim.square_size = 650 # The side length of the square that is the focus area. If nan/undecleared the entire TIF will be used

sim.centre_of_square_x = 4087 #The coordinates of the focus square
sim.centre_of_square_y = 1558

sim.type = "Loam" #prospect.type options: "Loam", "LoamX" and "Reverse-Loam". To be added - "prospectivityMap"

sim.sims = 100000 # The total number of simulations to perform

sim.multithreading_enabled = false # Untested multithreading code

#Either prospect.samples must be decleared or prospect.deposit must be, both can be decleared 


#Samples variables:

prospect.samples = [[100,100],[100,100]] # The relative (to the focus square) location of sample

prospect.samples_form = ["Coarse", "Fine"] # len(propsect.samples) must equal prospect prospect.samples_form

prospect.samples_weights = [0.5,0.1] # len(prospect.weights) must equal prospect prospect.samples_form. Weights need not add to one

#Deposit variables:

deposit.center_x = 100 # The relative (to the focus square) location of sample
deposit.center_y = 100 

deposit.trend = 50 # Trend (strike direction of the deposit)

deposit.length = 100 # Length of deposit

deposit.dip = 50 # Dip of the deposit

deposit.type = "Fine" # Deposit equivalent to samples.samples_form

# Display options

display.log = true # Display the log of probabilities

display.highlight_deposit = true # Highlight the deposit on the display


